// Bun script: turns the static export (out/) into server/assets.gen.ts, which
// scriptc compiles into the native server. Text assets are pre-compressed at
// maximum gzip level so the server never compresses at request time.
//
//   bun scripts/embed-assets.ts [outDir] [target]

import { Glob } from 'bun';
import { resolve, sep } from 'node:path';

const outDir = resolve(process.argv[2] ?? 'out');
const target = resolve(process.argv[3] ?? 'server/assets.gen.ts');

const TYPES: Record<string, string> = {
    html: 'text/html; charset=utf-8',
    txt: 'text/plain; charset=utf-8',
    js: 'text/javascript; charset=utf-8',
    mjs: 'text/javascript; charset=utf-8',
    css: 'text/css; charset=utf-8',
    json: 'application/json',
    map: 'application/json',
    svg: 'image/svg+xml',
    png: 'image/png',
    jpg: 'image/jpeg',
    jpeg: 'image/jpeg',
    gif: 'image/gif',
    webp: 'image/webp',
    ico: 'image/x-icon',
    woff: 'font/woff',
    woff2: 'font/woff2',
    ttf: 'font/ttf',
    webmanifest: 'application/manifest+json',
};
const COMPRESSIBLE = new Set(['html', 'txt', 'js', 'mjs', 'css', 'json', 'map', 'svg', 'ico', 'webmanifest', 'ttf']);

let rawTotal = 0;
let servedTotal = 0;
const lines: string[] = [];

for await (const file of new Glob('**/*').scan({ cwd: outDir, onlyFiles: true })) {
    const ext = file.slice(file.lastIndexOf('.') + 1).toLowerCase();
    if (ext === 'map') continue; // source maps stay out of production
    const bytes = new Uint8Array(await Bun.file(`${outDir}/${file}`).arrayBuffer());
    const type = TYPES[ext] ?? 'application/octet-stream';
    let gzip = '';
    if (COMPRESSIBLE.has(ext)) {
        const packed = Bun.gzipSync(bytes, { level: 9 });
        if (packed.length < bytes.length * 0.9) gzip = Buffer.from(packed).toString('base64');
    }
    const path = `/${file.split(sep).join('/')}`;
    const etag = `"${Bun.hash(bytes).toString(16)}"`;
    // Next.js content-hashes everything under /_next/static/.
    const immutable = path.startsWith('/_next/static/');

    rawTotal += bytes.length;
    servedTotal += gzip ? Buffer.from(gzip, 'base64').length : bytes.length;
    lines.push(`    new Asset(${JSON.stringify(path)}, ${JSON.stringify(type)}, ${JSON.stringify(Buffer.from(bytes).toString('base64'))}, ${JSON.stringify(gzip)}, ${JSON.stringify(etag)}, ${immutable}),`);
}

if (lines.length === 0) throw new Error(`no files in ${outDir}: run the static export first`);

await Bun.write(target, `// Generated by scripts/embed-assets.ts from the static export. Do not edit.
import { Asset } from "./asset";

export const ASSETS: Asset[] = [
${lines.sort().join('\n')}
];
`);

console.log(`embedded ${lines.length} files (${(rawTotal / 1e6).toFixed(2)} MB, ${(servedTotal / 1e6).toFixed(2)} MB as served) into ${target}`);
